dependencies:
  # the pattern is <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"

dotenv: .env
networks:
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
  ganache-local-nw:
    verify: False
  #default: - u can add a default network by yourself

wallets:
  from_key: ${PRIVATE_KEY}
